### ISSUE TITLE
Which VPNs are supported now and in the future?

### ISSUE THREAD

**Issue by DerMuffin** [Nekoraru22/Bing-Rewards-RP-free#1]
Hey!

Amazing Work. Do i need a specific VPN provider to get it work now?

What about the next release? Which VPN support the auto-switch feature?

Thanks!

**Comment by Nekoraru22** [comment]
Thank you!
You can use any VPN, im using now IpVanish but at the moment no VPN is automated, in the future i plan to automate IpVanish and probably NordVPN.

For the next release i want to fix the autoupdate (i have some problems with it xD), automate IpVanish and finish the monthly tasks

I'm also working on the IpVanish account checker, but hopefully you can find an account at: "https://blazealts.com/ipvanish/"
