### ISSUE TITLE
Stuck in doing tasks

### ISSUE THREAD

**Issue by Culetto** [Nekoraru22/Bing-Rewards-RP-free#2]
Hello, it seems that the new interface of Rewards broke the bot, when i'm in VPN mode in US everything works fine while doing searches but when it starts doing tasks that's where it gets stuck endlessly.
This doesn't happen when I am in my country, where there is still the old interface

**Comment by Nekoraru22** [comment]
Microsoft is currently testing new styles for the tasks, until they decide on a final style I cannot make changes to the program due to time issues and because mostly the old model is still in use

**Comment by Nekoraru22** [comment]
Microsoft is currently testing new styles for the tasks, until they decide on a final style I cannot make changes to the program due to time issues and because mostly the old model is still in use

**Comment by Culetto** [comment]
Fucking microsoft man

**Comment by Nekoraru22** [comment]
You can try to create a new profile and login into your account again, sometimes it can solve that problem.
